sectors.desc <- list( code17 = c("AZ",
                                 "DE",
                                 "C1",
                                 "C2",
                                 "C3",
                                 "C4",
                                 "C5",
                                 "FZ",
                                 "GZ",
                                 "HZ",
                                 "IZ",
                                 "JZ",
                                 "KZ",
                                 "LZ",
                                 "MN",
                                 "OQ",
                                 "RU"),
                      label_sectors_FR = c("Agriculture, sylviculture et pêche",
                                           "Industries extractives, énergie, eau, gestion des déchets et dépollution",
                                           "Fabrication de denrées alimentaires, de boissons et de produits à base de tabac",
                                           "Cokéfaction et raffinage",
                                           "Fabrication d'équipements électriques, électroniques, informatiques ; fabrication de machines",
                                           "Fabrication de matériels de transport",
                                           "Fabrication d'autres produits industriels",
                                           "Construction",
                                           "Commerce ; réparation d'automobiles et de motocycles",
                                           "Transports et entreposage",
                                           "Hébergement et restauration",
                                           "Information et communication",
                                           "Activités financières et d'assurance",
                                           "Activités immobilières",
                                           "Activités spécialisées, scientifiques et techniques et activités de services administratifs et de soutien",
                                           "Administration publique, enseignement, santé humaine et action sociale",
                                           "Autres activités de services"), 
                      
                      label_sectors_FR_plot = c("Agriculture, \n sylviculture et pêche",
                                                "Industries extractives, énergie, eau, \n gestion des déchets et dépollution",
                                                "Fabrication de denrées alimentaires,\n de boissons et de produits à base de tabac",
                                                "Cokéfaction et raffinage",
                                                "Fabrication d'équipements électriques,\n électroniques, informatiques ; \n fabrication de machines",
                                                "Fabrication de matériels de transport",
                                                "Fabrication d'autres \n produits industriels",
                                                "Construction",
                                                "Commerce ; réparation \n d'automobiles et de motocycles",
                                                "Transports et entreposage",
                                                "Hébergement et restauration",
                                                "Information et communication",
                                                "Activités financières \n et d'assurance",
                                                "Activités immobilières",
                                                "Activités spécialisées, \n scientifiques et techniques  \n et activités de services administratifs et de soutien",
                                                "Administration publique, enseignement,\n santé humaine et action sociale",
                                                "Autres activités de services"), 
                      
                      label_sectors_FR_short = c("Agriculture",
                                                 "Énergie, eau, déchets",
                                                 "Industries agro-alimentaires",
                                                 "Cokéfaction et raffinage",
                                                 "Biens d'équipement",
                                                 "Matériels de transport",
                                                 "Autres branches industrielles",
                                                 "Construction",
                                                 "Commerce",
                                                 "Transport",
                                                 "Hébergement-restauration",
                                                 "Information-communication",
                                                 "Services financiers",
                                                 "Services immobiliers",
                                                 "Services aux entreprises",
                                                 "Services non-marchands",
                                                 "Services aux ménages"),
                      
                      label_sectors = c("Agriculture, forestry and fishing",
                                         "Mining and quarrying, energy, water,\n waste management and remediation",
                                         "Manufacture of food, beverages \n and tobacco products",
                                         "Coking and refining",
                                         "Manufacture of electrical, electronic and \n computer equipment; machinery manufacturing",
                                         "Transport equipment manufacturing",
                                         "Manufacture of other industrial products",
                                         "Construction",
                                         "Trade ; repair of motor vehicles and motorcycles",
                                         "Transport and storage",
                                         "Accommodation and catering",
                                         "Information and communication",
                                         "Financial and insurance activities",
                                         "Real estate activities",
                                         "Specialized, scientific and technical activities \n and administrative and support service activities",
                                         "Public administration, education,\n human health and social work",
                                         "Other service activities")
)

